management:
    context-path: /internal

service:
  encryption:
    password: example
    salt: example

exampleservice:
  product-stream-name: synapse-example-products

logging:
    config: classpath:logback-console.xml

server:
  port: 5555