spring:
  application:
    name: synapse-edison-example

management:
  endpoints:
    web:
      exposure:
        include: '*'

edison:
  application:
    title:  Synapse + Edison Example
    description: Synapse µservice with support for edison-microservice
    group: synapse-examples
    environment: local

exampleservice:
  product-channel: example-products
  banana-channel: example-bananas

logging:
  config: classpath:logback-console.xml

server:
  port: 5555
#  servlet:
#    context-path: /example
