spring:
  application:
    name: Edison Example

edison:
  application:
    title:  Synapse + Edison Example
    description: Synapse µservice with support for edison-microservice
    group: synapse-examples
    environment: local

synapse:
  consumer-process:
    enabled: true
  edison:
    status:
      latency:
        enabled: true

exampleservice:
  product-channel: example-products
  banana-channel: example-bananas

logging:
  config: classpath:logback-console.xml

server:
  context-path: /
  port: 5555