spring:
  application:
    name: synapse-edison-example
edison:
  application:
    title:  Synapse + Edison Example
    description: Synapse µservice with support for edison-microservice
    group: synapse-examples
    environment: local

exampleservice:
  product-channel: example-products
  banana-channel: example-bananas

logging:
  config: classpath:logback-console.xml

server:
  context-path: /example
  port: 5555