spring:
  application:
    name: example-messagelog-consumer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: example-consumer-group

management:
  context-path: /internal

synapse:
  consumer-process:
    enabled: true

exampleservice:
  product-channel: example-products
  banana-channel: example-bananas

logging:
    config: classpath:logback-console.xml

server:
  port: 5555