sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - docker pull localstack/localstack
  - export AWS_ACCESS_KEY_ID=localstack
  - export AWS_SECRET_ACCESS_KEY=localstack
  - export REGION=eu-central-1

install: /bin/true # skip gradle assemble

script: ./gradlew check --info
