aws:
  profile: edison-aws-test
  region: eu-central-1

management:
    context-path: /internal

edison:
  eventsourcing:
    snapshot:
      enabled: true
      bucket-template: snapshot-{stream-name}
    event-source-consumer-process:
      enabled: true

exampleservice:
  product-stream-name: edison-example-products
  banana-stream-name: edison-example-bananas

logging:
    config: classpath:logback-console.xml

server:
  port: 5555